### ISSUE TITLE
imx8mp-a0-nitrogen8mp.dtb not found 

### ISSUE THREAD

**Issue by bwhitman** [boundarydevices/linux#69]
Hi I have a nitrogen8mp board, rev 2020-10-08. I am using the Yocto HOWTO here: https://boundarydevices.com/yocto-hardknott-release-for-i-mx8-platforms/

The board does not boot, saying it cannot find "imx8mp-a0-nitrogen8mp.dtb" in the U-boot console. This is nowhere in the yocto build files. Instead, there is a imx8mp-nitrogen8mp.dtb . If I rename the DTB the board continues to boot but pauses after the line
```
[    2.642292] sdhci: Secure Digital Host Controller Interface driver
[    2.648488] sdhci: Copyright(c) Pierre Ossman
[    2.652974] Synopsys Designware Multimedia Card Interface Driver
[    2.659207] sdhci-pltfm: SDHCI platform and OF driver helper

U-Boot SPL 2020.10-52789-g0d6d735cef (Apr 16 2021 - 05:29:15 -0700)
config to do 4000 1d training.
config to do 400 1d training.
```

And eventually reboots. Any idea how to get this rev of board working for yocto hardknott?

**Comment by gibsson** [comment]
Hi,
Yes the A0 support has been removed after the first release as NXP dropped its support after the last beta release.
The A0 was a pre-production silicon only meant for early adopters. We recommend getting a production version of the SOM in order to use any of the latest SW. Please reach out to info@boundarydevices.com for more info.
